### ISSUE TITLE
Support of string values for SNMP variables

### ISSUE THREAD

**Issue by marcoscereijo** [sonata-nfv/son-monitor#111]
In our VNFs we are returning some numeric SNMP values as STRING since it the format provided by default by the EXTEND-MIB variables. 

```
ubuntu@wac-vnf:~$ snmpwalk -v 3 -l authPriv -u "quobis" -a sha -A "5gt4ng00" -x aes -X "5gt4ng00" "localhost" .1.3.6.1.4.1.8072.1.3.2.3.1.2.22.115.105.112.112.111.83.101.114.118.101.114.67.111.110.102.101.114.101.110.99.101.115
iso.3.6.1.4.1.8072.1.3.2.3.1.2.22.115.105.112.112.111.83.101.114.118.101.114.67.111.110.102.101.114.101.110.99.101.115 = STRING: "25"
```

```
ubuntu@wac-vnf:~$  snmpwalk -v 3 -l authPriv -u "quobis" -a sha -A "5gt4ng00" -x aes -X "5gt4ng00" "localhost" NET-SNMP-EXTEND-MIB::nsExtendOutputFull.\"sippoServerConferences\"
NET-SNMP-EXTEND-MIB::nsExtendOutputFull."sippoServerConferences" = STRING: 0
```

Will this mean a problem for the monitoring tool?

In this example: https://github.com/sonata-nfv/tng-y1-demo/blob/master/tango/squid/Definitions/squid_vnf.yaml we see that the variables are defined this way:

```
oids:
        - oid: "1.3.6.1.4.1.3495.1.1.3.0"
          metric_name: "cacheUptime"
          metric_type: "gauge"
          unit: "secs"
          mib_name: "SQUID-MIB"
```

We are planning to deifne it as follows, but we have some doubts:
```
oids:
        - oid: "1.3.6.1.4.1.8072.1.3.2.3.1.2.22.115.105.112.112.111.83.101.114.118.101.114.67.111.110.102.101.114.101.110.99.101.115"
          metric_name: "sippoServerConferences"
          metric_type: "gauge" ???
          unit: "number" ???
          mib_name: "NET-SNMP-EXTEND-MIB" ??
```

Do you know what values must we set in the field with '???' we don't know if those values must be understood by the platform, we think so. Are the possible values defined anywhere?

Thanks in advance
